---
- hosts: local
  connection: local
  vars:
    filters:
      "tag:name": ike-drilling
  vars_files:
    - aws_keys.yml
    - vars.yml
  tasks:
    - name: "Gather EC2 info"
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        filters: 
          "tag:Name": "{{ instance_name }}"
      register: ec2
    - name: "Gather VPC info"
      ec2_vpc_net_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        filters: 
          "tag:Name": "{{ vpc_name }}"
          cidr-block: "{{ vpc_cidr }}"
      register: vpc_info
      
    - name: Terminate drilling EC2
      ec2_instance:
#        name: "{{ instance_name }}"
        instance_ids: '{{ ec2.instances[0].instance_id }}'
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        wait: true
        termination_protection: false
        
    - name: Delete security group
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ security_group }}"
        region: "{{ region }}"
        state: absent
        
        
    - name: Delete IGW
      ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: absent
        tags:
          name: "{{ igw_name }}"
    - name: Delete route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        tags:
          Name: Internet
        state: absent
    - name: Delete subnet 
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        cidr: "{{ subnet_cidr }}"
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource_tags:
          Name: "{{ subnet_name }}"
          
    - name: "Delete VPC"
      ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        cidr_block: "{{ vpc_cidr }}"
        name: "{{ vpc_name }}"
        state: absent
        
    - name: Delete S3 bucket
      s3_bucket:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ bucket_name }}"
        force: true
        state: absent
    