---
- hosts: local
  connection: local
  vars:
    filters:
      "tag:name": ike-drilling
  vars_files:
    - aws_keys.yml
    - vars.yml
  tasks:
    - name: "Gather EC2 info"
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        filters: "{{ filters }}"
      register: ec2
    - name: "Gather VPC info"
      ec2_vpc_net_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        filters: "{{ filters }}"
      register: vpcs
      
    - name: Terminate drilling EC2
      ec2_instance:
        name: "{{ instance_name }}"
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        
        
    - name: Delete security group
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ security_group }}"
        region: "{{ region }}"
        state: absent
        
    - name: Delete IGW
      ec2_vpc_igw:
        vpc_id: "{{ vpcs.vpc_id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: absent
        tags:
          name: "{{ igw_name }}"
          
    - name: Delete subnet 
      ec2_vpc_subnet:
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource_tags:
          Name: "{{ subnet_name }}"
          
    - name: "Delete VPC"
      ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        cidr_block: "{{ vpc_cidr }}"
        name: "{{ vpc_name }}"
        state: absent
    