---
- hosts: local
  connection: local
  vars:
  vars_files:
    - aws_keys.yml
    - vars.yml
  tasks:
    - name: "Delete VPC"
      ec2_elb_lb:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: "{{ vpc_name }}"
        state: absent
    