version: '3'
services:
  reader:
    hostname: reader
    environment: {}
    ports:
    - "3000:3000"
    image: reader:latest
    restart: always
#    networks:
#    - vlan
  writer:
    hostname: writer
    environment: {}
    ports:
    - "37529:37529"
    image: writer:latest
    restart: always
#    networks:
#    - vlan
    volumes:
    - /var/bucket:/var/bucket

#volumes:
#    drilling-logs: {}

#networks:
#    vlan:
#       driver: bridge
