version: '3'
services:
  reader:
    hostname: reader
    environment: {}
    ports:
    - "3000:3000"
    image: reader:latest
    restart: always
  writer:
    hostname: writer
    environment: {}
    ports:
    - "37529:37529"
    image: writer:latest
    restart: always
    volumes:
    - /var/bucket:/var/bucket

