version: '3'
services:
  reader:
    hostname: reader
    environment: {}
    ports:
    - "3000:3000"
    image: dockerhub.cisco.com/vge-docker-staging/smp:20180315044337-4.0.0-2
    networks:
    - vlan
  writer:
    hostname: writer
    environment: {}
    ports:
    - "37529:37529"
    image: dockerhub.cisco.com/vge-docker-staging/vxb2:20180315134227-4.0.0-12
    networks:
    - vlan
    volumes:
    - /var/bucket:/var/bucket

volumes:
    drilling-logs: {}

networks:
    vlan:
       driver: bridge
